### ISSUE TITLE
I'm getting error

### ISSUE THREAD

**Issue by aymenitc** [Nikolai2038/webp-to-gif#1]
[webp @ 0x56525c03e700] skipping unsupported chunk: ANIM
[webp @ 0x56525c03e700] skipping unsupported chunk: ANMF
    Last message repeated 42 times
[webp_pipe @ 0x56525c03c6c0] decoding for stream 0 failed
[webp_pipe @ 0x56525c03c6c0] Could not find codec parameters for stream 0 (Video: webp, none): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, webp_pipe, from './media/anisticker.webp':
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: webp, none, 25 tbr, 25 tbn, 25 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (webp (native) -> png (native))
Press [q] to stop, [?] for help
[webp @ 0x56525c051ec0] skipping unsupported chunk: ANIM
[webp @ 0x56525c051ec0] skipping unsupported chunk: ANMF
    Last message repeated 42 times
Error while decoding stream #0:0: Invalid data found when processing input
Cannot determine format of input stream 0:0 after EOF
Error marking filters as finished
Conversion failed!

Used file:
https://drive.google.com/file/d/1wafYmaZDtb8I7yJ9CgvlINV5i0eSiHGu/view?usp=drivesdk

**Comment by Nikolai2038** [comment]
Hi, thanks for the reply!

I reproduced this and looked into it. It seems like `ffmpeg` cannot decode `ANIM` and `ANIMF` yet (and has been for so many years) - found [this ticket](https://trac.ffmpeg.org/ticket/4907) from [this issue](https://github.com/tanersener/mobile-ffmpeg/issues/378) on some project. On the ticket page there are links to some other files too, on which this problem can be reproduced.

From the ticket there is a link to a [patch](https://patchwork.ffmpeg.org/project/ffmpeg/patch/20210908184931.3620755-1-yakoyoku@gmail.com/) on `ffmpeg` from some developer, but it was not finished (created two years ago). So I don't think this will be implemented soon.

I will look into some alternatives to decode `webp`/`webm`. I will comment here if I get any results 😉

**Comment by aymenitc** [comment]
Thanks a lot of replying

**Comment by Nikolai2038** [comment]
Hey!

I found [this solution](https://askubuntu.com/questions/1140873/how-can-i-convert-an-animated-webp-to-a-webm/1141049#1141049) and implemented it via Docker container. This can also applied to the raw system, so I add instructions for that too. I adapted scripts and tested them on several images, yours too - it worked. The size can be a problem, but it's for future.

I also added new example files (your is named `./data/examples/07_anisticker.gif`) and these are the results I got:

1. `./convert_one.sh ./data/examples/07_anisticker.webp 0 0` (5134Kb):

   ![07_anisticker](https://github.com/Nikolai2038/webp-to-gif/assets/70556725/17d96eac-7b60-4e2f-aa54-013511267525)

2. `./convert_one.sh ./data/examples/07_anisticker.webp 1 0` (6175 Kb):

   ![07_anisticker](https://github.com/Nikolai2038/webp-to-gif/assets/70556725/9ef1a196-ce0d-498f-9977-c3bca25cdb8f)

3. `./convert_one.sh ./data/examples/07_anisticker.webp 0 1` (4458 Kb):

   ![07_anisticker](https://github.com/Nikolai2038/webp-to-gif/assets/70556725/690f2f0e-196f-47c0-95e4-9e3d893c412d)

4. `./convert_one.sh ./data/examples/07_anisticker.webp 1 1` (3197 Kb):

   ![07_anisticker](https://github.com/Nikolai2038/webp-to-gif/assets/70556725/2ef49af9-c54d-436a-96b1-0d765dd636a4)

5. `./convert_one.sh ./data/examples/07_anisticker.webp 0 2` (4113 Kb):

   ![07_anisticker](https://github.com/Nikolai2038/webp-to-gif/assets/70556725/d4d5caf9-daab-41b7-95c5-212566068d51)

6. `./convert_one.sh ./data/examples/07_anisticker.webp 1 2` (1581 Kb):

   ![07_anisticker](https://github.com/Nikolai2038/webp-to-gif/assets/70556725/9c7ca35b-95bd-4138-bb44-1882c515a4b7)

It seems that for some reason enabling transparency can significantly reduce `gif` size, when using compression levels `0` and `1` (this compression levels created by me and applying different settings to `gifsicle`). The result is not that great, but it seems, this not always the case - other examples can produce good image sizes:

```bash
./test.sh 1 1
```

Results:

```
150K    01_girl.gif
195K    01_girl.webp
969K    02_cube.gif
372K    02_cube.webp
55K     03_animated_rgb.gif
37K     03_animated_rgb.webp
139K    04_animated_yuv.gif
67K     04_animated_yuv.webp
563K    05_not_animated.gif
1.3M    05_not_animated.webp
311K    06_animated_yuv_transparent.gif
150K    06_animated_yuv_transparent.webp
3.2M    07_anisticker.gif
354K    07_anisticker.webp
```

You can test it and share results 😉

I think scripts can be improved, so if they get more attention, I will look into it (need more knowledge on `ffmpeg` and `gifsicle` commands)

**Comment by Nikolai2038** [comment]
Also, I renamed the repository from `bash-webp-to-gif` to just `webp-to-gif`, so you might need to clone it again or change links in `./.git/config` file

**Comment by aymenitc** [comment]
Ok thanks a lot. I really appreciate your help 🙏

**Comment by aymenitc** [comment]
Tested. It is working 😀. Thanks
